Consolidate ARM into AUR repo

diff --git a/.github/workflows/repo.yaml b/.github/workflows/repo.yaml
--- a/.github/workflows/repo.yaml
+++ b/.github/workflows/repo.yaml
@@ -7,7 +7,7 @@ on:
     - cron:  '1 7 * * 0'
 
 jobs:
-  build:
+  build-x86_64:
     runs-on: ubuntu-latest
     name: Build on x64_64
     container:
@@ -83,5 +83,100 @@ jobs:
             ```
           files: |
             ${{ github.workspace }}/*
+          draft: false
+          prerelease: false
+
+  build-arm:
+    runs-on: ubuntu-latest
+    name: Build on ${{ matrix.arch }}
+
+    strategy:
+      matrix:
+        include:
+          - arch: aarch64
+          - arch: armv7
+
+    steps:
+      - name: Set variables
+        id: set-vars
+        run: |
+          echo "::set-output name=date::$(date +'%Y-%m-%d %H:%M')"
+          echo "::set-output name=repo-id::$(echo ${{ github.repository }} | sed 's/\//-/g')"
+
+      - name: Build packages
+        id: package
+        uses: uraimo/run-on-arch-action@v2.0.9
+        with:
+          arch: ${{ matrix.arch }}
+          distro: archarm_latest
+
+          githubToken: ${{ secrets.GITHUB_TOKEN }}
+
+          dockerRunArgs: |
+            --volume "${{ runner.temp }}:/workspace"
+
+          env: |
+            AUR_ASROOT: 1
+            PKGEXT: .pkg.tar.zst
+            REPO_IDENTIFIER: ${{ steps.set-vars.outputs.repo-id }}
+            INSTALL_PACKAGES: jre11-openjdk-headless
+            BUILD_PACKAGES: watchdog uhubctl runrestic openhab3 openhab3-addons
+
+          shell: /bin/sh
+
+          run: |
+            pacman -Syyu --noconfirm
+            pacman -S base-devel --noconfirm
+            pacman -S ${INSTALL_PACKAGES} --noconfirm
+            sed -i 's,exit $E_ROOT,echo but you know what you do,' /usr/bin/makepkg
+            cd /tmp
+            curl --output aurutils.tar.gz https://aur.archlinux.org/cgit/aur.git/snapshot/aurutils.tar.gz
+            tar xf aurutils.tar.gz
+            cd aurutils
+            makepkg --syncdeps --noconfirm
+            pacman -U --noconfirm aurutils-*.pkg.tar.zst
+            cp -v /tmp/aurutils/aurutils-*.pkg.tar.zst /workspace
+            echo "::set-output name=arch::$(uname -m)"
+            repo-add /workspace/${REPO_IDENTIFIER}.db.tar.gz /workspace/aurutils-*.pkg.tar.zst
+            echo "setting up repo"
+            echo "# local repository (required by aur tools to be set up)" >> /etc/pacman.conf
+            echo "[${REPO_IDENTIFIER}]" >> /etc/pacman.conf
+            echo "SigLevel = Optional TrustAll" >> /etc/pacman.conf
+            echo "Server = file:///workspace " >> /etc/pacman.conf
+            aur sync -A --noconfirm --noview --database ${REPO_IDENTIFIER} --root /workspace $BUILD_PACKAGES
+
+      - name: Remove symbolic links
+        run: |
+          cd "${{ runner.temp }}"
+          ls -al
+          rm -v ${{ steps.set-vars.outputs.repo-id }}.db ${{ steps.set-vars.outputs.repo-id }}.files
+          cp -v ${{ steps.set-vars.outputs.repo-id }}.db.tar.gz ${{ steps.set-vars.outputs.repo-id }}.db
+          cp -v ${{ steps.set-vars.outputs.repo-id }}.files.tar.gz ${{ steps.set-vars.outputs.repo-id }}.files
+          rm -fv build-log.txt *.sh
+          ls -al
+
+      - name: Remove release
+        uses: kopp/action-delete-release@v1
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          tag_name: ${{ steps.package.outputs.arch }}
+
+      - name: Upload release
+        uses: softprops/action-gh-release@v1
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          tag_name: ${{ steps.package.outputs.arch }}
+          name: Arch Linux ARM AUR Build ${{ github.run_number }} from ${{ steps.set-vars.outputs.date }} for ${{ steps.package.outputs.arch }}
+          body: |
+            To use this repository, please append the following to `/etc/pacman.conf`:
+            ```
+            [${{ steps.set-vars.outputs.repo-id }}]
+            SigLevel = Optional TrustAll
+            Server = https://github.com/${{ github.repository }}/releases/download/${{ steps.package.outputs.arch }}
+            ```
+          files: |
+            ${{ runner.temp }}/*
           draft: false
           prerelease: false
