Build packages individually

diff --git a/.github/workflows/repo.yaml b/.github/workflows/repo.yaml
--- a/.github/workflows/repo.yaml
+++ b/.github/workflows/repo.yaml
@@ -73,7 +73,11 @@ jobs:
           sudo -u auruser aur sync --sign -A --noconfirm --noview --database ${REPO_IDENTIFIER} --root ${GITHUB_WORKSPACE} photoprism
           pacman -Rs --noconfirm tensorflow115
           pacman -S --noconfirm python-pip python-tensorflow python-pillow
-          sudo -u auruser aur sync --sign -A --noconfirm --noview --database ${REPO_IDENTIFIER} --root ${GITHUB_WORKSPACE} jellyfin ledger-udev ledger-live-bin paru brother-mfc-l8690cdw zoom google-chrome ipmiview jackett sonarr radarr pipman-git archivemail reposilite laminar bacula-common bacula-client mtx-svn mt-st-git rtsptoweb
+          for pkg in etesync-dav jellyfin ledger-udev ledger-live-bin paru brother-mfc-l8690cdw zoom google-chrome ipmiview jackett sonarr radarr pipman-git archivemail reposilite laminar bacula-common bacula-client mtx-svn mt-st-git rtsptoweb
+          do
+            echo "### Package ${pkg}"
+            sudo -u auruser aur sync --sign -A --noconfirm --noview --database ${REPO_IDENTIFIER} --root ${GITHUB_WORKSPACE} ${pkg} || echo "!!! Package ${pkg} failed"
+          done
           chmod -R 777 ${GITHUB_WORKSPACE}
 
       - name: Remove symbolic links
